_registry_: "model"
_type_: LigandDecoderV3
d_equi: 96
d_inv: 384
d_edge: 128
n_layers: 8
n_attn_heads: 64 # n heads = 6
d_message: 128
d_message_ff: 256
d_pocket_inv: ???
d_pocket_equi: ???
time_cond_dim: 3 # NOTE: for CGFlow (time;rel time; gen time)
self_cond: True
