# save dir
result_dir: "./result/opt/unidock_qed/aldh1"

# environment
env_dir: ./data/envs/enamine_stock
max_atoms: 40 # maximum atom counts
subsampling_ratio: 0.1 # Memory-variance trade-off

# docking
protein_path: ./data/examples/aldh1_protein.pdb
center: null # search box center
ref_ligand_path: ./data/examples/aldh1_ligand.mol2 # to determine the center
size: [22.5, 22.5, 22.5] # search box size

# opt
num_steps: 2000
num_sampling_per_step: 32
temperature: [1, 64] # uniform(1, 64)
seed: 1

# pose prediction
pose_model: "./weights/cgflow_crossdock.ckpt"
pose_steps: 40

# extras
sampling_tau: 0.9 # EMA
random_action_prob: 0.05 # suggest to set positive value
replay_warmup_step: 10 # 10 steps
replay_capacity: 6400
